[database]
host     = {{env "CHATAPP_DATABASE_HOST"}}
port     = {{env "CHATAPP_DATABASE_PORT"}}
user     = {{env "CHATAPP_DATABASE_USER"}}
password = {{env "CHATAPP_DATABASE_PASSWORD"}}
database = {{env "CHATAPP_DATABASE_NAME"}}
