// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chats.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addChatParticipant = `-- name: AddChatParticipant :exec
INSERT INTO chat_participants (chat_id, user_id)
VALUES ($1, $2)
`

type AddChatParticipantParams struct {
	ChatID uuid.UUID `json:"chat_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) AddChatParticipant(ctx context.Context, arg AddChatParticipantParams) error {
	_, err := q.db.Exec(ctx, addChatParticipant, arg.ChatID, arg.UserID)
	return err
}

const chatParticipantIDs = `-- name: ChatParticipantIDs :many
SELECT user_id
FROM chat_participants
WHERE chat_id = $1
`

// Fan-out targets for a chat: everyone in it, sender included.
func (q *Queries) ChatParticipantIDs(ctx context.Context, chatID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, chatParticipantIDs, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createChat = `-- name: CreateChat :one
INSERT INTO chats (title)
VALUES (NULL)
RETURNING id
`

func (q *Queries) CreateChat(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createChat)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteChat = `-- name: DeleteChat :exec
DELETE FROM chats
WHERE id = $1
`

// Hard delete; cascades to chat_participants and messages.
func (q *Queries) DeleteChat(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChat, id)
	return err
}

const friendshipExists = `-- name: FriendshipExists :one
SELECT EXISTS (
    SELECT 1
    FROM chat_participants a
    JOIN chat_participants b ON b.chat_id = a.chat_id
    JOIN chats c ON c.id = a.chat_id
    WHERE a.user_id = $1
      AND b.user_id = $2
      AND c.deleted_at IS NULL
)
`

type FriendshipExistsParams struct {
	UserID   uuid.UUID `json:"user_id"`
	UserID_2 uuid.UUID `json:"user_id_2"`
}

// Guards ErrAlreadyFriends: do the two users already share a chat?
func (q *Queries) FriendshipExists(ctx context.Context, arg FriendshipExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, friendshipExists, arg.UserID, arg.UserID_2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isChatParticipant = `-- name: IsChatParticipant :one
SELECT EXISTS (
    SELECT 1
    FROM chat_participants
    WHERE chat_id = $1 AND user_id = $2
)
`

type IsChatParticipantParams struct {
	ChatID uuid.UUID `json:"chat_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) IsChatParticipant(ctx context.Context, arg IsChatParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChatParticipant, arg.ChatID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listChatsForUser = `-- name: ListChatsForUser :many
SELECT c.id AS chat_id,
       u.id AS other_user_id,
       u.username AS other_username,
       last.content AS last_message,
       last.sent_at AS last_message_at,
       (SELECT COUNT(*)
        FROM messages um
        WHERE um.chat_id = c.id
          AND um.sender_id <> $1
          AND um.read_at IS NULL) AS unread_count
FROM chat_participants self
JOIN chats c ON c.id = self.chat_id
JOIN chat_participants other
  ON other.chat_id = self.chat_id AND other.user_id <> self.user_id
JOIN users u ON u.id = other.user_id
LEFT JOIN messages last ON last.id = (
    SELECT m.id
    FROM messages m
    WHERE m.chat_id = c.id
    ORDER BY m.sent_at DESC
    LIMIT 1
)
WHERE self.user_id = $1
  AND c.deleted_at IS NULL
ORDER BY COALESCE(last.sent_at, c.created_at) DESC
`

type ListChatsForUserRow struct {
	ChatID        uuid.UUID   `json:"chat_id"`
	OtherUserID   uuid.UUID   `json:"other_user_id"`
	OtherUsername string      `json:"other_username"`
	LastMessage   pgtype.Text `json:"last_message"`
	LastMessageAt *time.Time  `json:"last_message_at"`
	UnreadCount   int64       `json:"unread_count"`
}

// The caller's chats with the other participant, a last-message preview and the
// caller's unread count.
// The preview is a plain LEFT JOIN (not a LATERAL) so that sqlc infers the
// preview columns as nullable: a chat with no messages yet still appears, with
// last_message/last_message_at NULL.
// The unread count is a correlated subquery rather than a JOIN … GROUP BY:
// aggregating here would drag every other selected column into the GROUP BY.
// It hits idx_messages_unread.
func (q *Queries) ListChatsForUser(ctx context.Context, senderID uuid.UUID) ([]ListChatsForUserRow, error) {
	rows, err := q.db.Query(ctx, listChatsForUser, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatsForUserRow
	for rows.Next() {
		var i ListChatsForUserRow
		if err := rows.Scan(
			&i.ChatID,
			&i.OtherUserID,
			&i.OtherUsername,
			&i.LastMessage,
			&i.LastMessageAt,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriends = `-- name: ListFriends :many
SELECT c.id AS chat_id, u.id AS user_id, u.username
FROM chat_participants self
JOIN chats c ON c.id = self.chat_id
JOIN chat_participants other
  ON other.chat_id = self.chat_id AND other.user_id <> self.user_id
JOIN users u ON u.id = other.user_id
WHERE self.user_id = $1
  AND c.deleted_at IS NULL
ORDER BY c.created_at DESC
`

type ListFriendsRow struct {
	ChatID   uuid.UUID `json:"chat_id"`
	UserID   uuid.UUID `json:"user_id"`
	Username string    `json:"username"`
}

func (q *Queries) ListFriends(ctx context.Context, userID uuid.UUID) ([]ListFriendsRow, error) {
	rows, err := q.db.Query(ctx, listFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendsRow
	for rows.Next() {
		var i ListFriendsRow
		if err := rows.Scan(&i.ChatID, &i.UserID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
