// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friend_invitations.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFriendInvitation = `-- name: CreateFriendInvitation :one
INSERT INTO friend_invitations (from_user_id, to_user_id)
VALUES ($1, $2)
RETURNING id
`

type CreateFriendInvitationParams struct {
	FromUserID uuid.UUID `json:"from_user_id"`
	ToUserID   uuid.UUID `json:"to_user_id"`
}

func (q *Queries) CreateFriendInvitation(ctx context.Context, arg CreateFriendInvitationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createFriendInvitation, arg.FromUserID, arg.ToUserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM friend_invitations
WHERE id = $1
`

func (q *Queries) DeleteInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvite, id)
	return err
}

const getInviteByID = `-- name: GetInviteByID :one
SELECT id, from_user_id, to_user_id, accepted_at, created_at
FROM friend_invitations
WHERE id = $1
FOR UPDATE
`

// FOR UPDATE so that inside the accept transaction two concurrent accepts of the
// same invite serialize; the second one then sees accepted_at set.
func (q *Queries) GetInviteByID(ctx context.Context, id uuid.UUID) (FriendInvitation, error) {
	row := q.db.QueryRow(ctx, getInviteByID, id)
	var i FriendInvitation
	err := row.Scan(
		&i.ID,
		&i.FromUserID,
		&i.ToUserID,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingInvitesForUser = `-- name: ListPendingInvitesForUser :many
SELECT fi.id, fi.from_user_id, u.username AS from_username, fi.created_at
FROM friend_invitations fi
JOIN users u ON u.id = fi.from_user_id
WHERE fi.to_user_id = $1
  AND fi.accepted_at IS NULL
ORDER BY fi.created_at DESC
`

type ListPendingInvitesForUserRow struct {
	ID           uuid.UUID `json:"id"`
	FromUserID   uuid.UUID `json:"from_user_id"`
	FromUsername string    `json:"from_username"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) ListPendingInvitesForUser(ctx context.Context, toUserID uuid.UUID) ([]ListPendingInvitesForUserRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitesForUser, toUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingInvitesForUserRow
	for rows.Next() {
		var i ListPendingInvitesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.FromUsername,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteAccepted = `-- name: MarkInviteAccepted :exec
UPDATE friend_invitations
SET accepted_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkInviteAccepted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInviteAccepted, id)
	return err
}

const pendingInviteExists = `-- name: PendingInviteExists :one
SELECT EXISTS (
    SELECT 1
    FROM friend_invitations
    WHERE accepted_at IS NULL
      AND ((from_user_id = $1 AND to_user_id = $2)
        OR (from_user_id = $2 AND to_user_id = $1))
)
`

type PendingInviteExistsParams struct {
	FromUserID uuid.UUID `json:"from_user_id"`
	ToUserID   uuid.UUID `json:"to_user_id"`
}

// Guards ErrInviteExists: a pending invite in EITHER direction blocks a new one.
func (q *Queries) PendingInviteExists(ctx context.Context, arg PendingInviteExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, pendingInviteExists, arg.FromUserID, arg.ToUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
