// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (chat_id, sender_id, content)
SELECT $1, $2, $3
WHERE EXISTS (
    SELECT 1
    FROM chat_participants
    WHERE chat_id = $1 AND user_id = $2
)
RETURNING id, chat_id, sender_id, content, sent_at
`

type CreateMessageParams struct {
	ChatID   uuid.UUID `json:"chat_id"`
	SenderID uuid.UUID `json:"sender_id"`
	Content  string    `json:"content"`
}

// Authorization and the write are one statement: the row is only inserted if the
// sender participates in the chat, so a non-participant gets no row back rather
// than a persisted message. "no rows" maps to ErrNotParticipant.
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ChatID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.Content,
		&i.SentAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, chat_id, sender_id, content, sent_at
FROM messages
WHERE chat_id = $1
  AND sent_at < $2
ORDER BY sent_at DESC
LIMIT $3
`

type ListMessagesParams struct {
	ChatID uuid.UUID `json:"chat_id"`
	SentAt time.Time `json:"sent_at"`
	Limit  int32     `json:"limit"`
}

// Newest-first page of a chat's history, walking backwards from the `before`
// cursor. Uses idx_messages_chat_sent.
func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ChatID, arg.SentAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Content,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
