// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package pgstore

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (chat_id, sender_id, content)
SELECT $1, $2, $3
WHERE EXISTS (
    SELECT 1
    FROM chat_participants
    WHERE chat_id = $1 AND user_id = $2
)
RETURNING id, chat_id, sender_id, content, sent_at, read_at
`

type CreateMessageParams struct {
	ChatID   uuid.UUID `json:"chat_id"`
	SenderID uuid.UUID `json:"sender_id"`
	Content  string    `json:"content"`
}

// Authorization and the write are one statement: the row is only inserted if the
// sender participates in the chat, so a non-participant gets no row back rather
// than a persisted message. "no rows" maps to ErrNotParticipant.
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ChatID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.Content,
		&i.SentAt,
		&i.ReadAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, chat_id, sender_id, content, sent_at, read_at
FROM messages
WHERE chat_id = $1
  AND sent_at < $2
ORDER BY sent_at DESC
LIMIT $3
`

type ListMessagesParams struct {
	ChatID uuid.UUID `json:"chat_id"`
	SentAt time.Time `json:"sent_at"`
	Limit  int32     `json:"limit"`
}

// Newest-first page of a chat's history, walking backwards from the `before`
// cursor. Uses idx_messages_chat_sent.
func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ChatID, arg.SentAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Content,
			&i.SentAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChatRead = `-- name: MarkChatRead :one
WITH marked AS (
    UPDATE messages
    SET read_at = NOW()
    WHERE chat_id = $1
      AND sender_id <> $2
      AND read_at IS NULL
    RETURNING id
)
SELECT COUNT(*) AS marked_count, NOW()::timestamptz AS read_at
FROM marked
`

type MarkChatReadParams struct {
	ChatID   uuid.UUID `json:"chat_id"`
	SenderID uuid.UUID `json:"sender_id"`
}

type MarkChatReadRow struct {
	MarkedCount int64     `json:"marked_count"`
	ReadAt      time.Time `json:"read_at"`
}

// Marks the caller's unread inbox for one chat. Only messages the caller did
// NOT send, and only ones still unread, so read_at is written exactly once and
// never moves. Participation is checked by the service before this runs.
//
// The UPDATE is wrapped in a CTE so the statement returns a single row however
// many messages it touched — a bare `RETURNING read_at` returns one row per
// updated message, which :one cannot express.
//
// The timestamp is re-derived with NOW() rather than aggregated out of the
// CTE's RETURNING. NOW() is transaction_timestamp(), constant for the whole
// statement, so it is exactly the value the UPDATE wrote — and it types as a
// plain non-null timestamptz, which MAX(read_at) over a data-modifying CTE does
// not (sqlc infers interface{} without a cast and NOT NULL with one, and this
// row exists even when zero messages were marked). marked_count == 0 is what
// the service reads as a no-op, so the timestamp is never consulted then.
func (q *Queries) MarkChatRead(ctx context.Context, arg MarkChatReadParams) (MarkChatReadRow, error) {
	row := q.db.QueryRow(ctx, markChatRead, arg.ChatID, arg.SenderID)
	var i MarkChatReadRow
	err := row.Scan(&i.MarkedCount, &i.ReadAt)
	return i, err
}
